import Head from "next/head";
import Footer from "./footer/Footer";
import MobileFooter from "./footer/MobileFooter";
import Header from "./header/Header";

export default function Layout({children}) {
  return (
  <>
      <Head>
        <title>Real Vision Hardware</title>  
        <meta charset="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="palabra clave 1, palabra clave 2, palabra clave 3"/>
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      {children}
      {/* <Footer /> */}
      <MobileFooter />
  </>
  );
}
