/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: paxillop (https://sketchfab.com/paxillop)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/pc-gaming-ryzen-nvidia-1660-a8477b1bcafa46ffb66af25e287fd098
title: Pc Gaming Ryzen Nvidia 1660
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/pcgamer.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.aiStandardSurface3SG} />
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.aiStandardSurface14SG} />
        <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
        <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
        <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
        <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
        <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
        <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
        <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
        <mesh geometry={nodes.mesh_13.geometry} material={materials.aiStandardSurface5SG} />
        <mesh geometry={nodes.mesh_14.geometry} material={materials.aiStandardSurface8SG} />
        <mesh geometry={nodes.mesh_15.geometry} material={materials.aiStandardSurface9SG} />
        <mesh geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} />
        <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
        <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
        <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
        <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
        <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} />
        <mesh geometry={nodes.mesh_22.geometry} material={materials.conectores_0014aiStandardSurface5SG} />
        <mesh geometry={nodes.mesh_23.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/pcgamer.gltf')
